// <auto-generated />
using System;
using GoTravel.Darwin.Domain.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace GoTravel.Darwin.Migrations
{
    [DbContext(typeof(GoTravelDarwinContext))]
    partial class GoTravelDarwinContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "postgis");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("GoTravel.Darwin.Domain.Models.Database.TimetableEntry", b =>
                {
                    b.Property<string>("RID")
                        .HasColumnType("text");

                    b.Property<bool>("Cancelled")
                        .HasColumnType("boolean");

                    b.Property<int?>("CancelledReason")
                        .HasColumnType("integer");

                    b.Property<int?>("LateReason")
                        .HasColumnType("integer");

                    b.Property<string>("Operator")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("date");

                    b.Property<string>("TrainHeadcode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("RID");

                    b.HasIndex("Operator");

                    b.ToTable("TimetableEntries", (string)null);
                });

            modelBuilder.Entity("GoTravel.Darwin.Domain.Models.Database.TimetableEntryLocation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ActivityType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("Cancelled")
                        .HasColumnType("boolean");

                    b.Property<bool>("Delayed")
                        .HasColumnType("boolean");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Platform")
                        .HasColumnType("text");

                    b.Property<DateTime?>("PredictedArrival")
                        .HasColumnType("timestamptz");

                    b.Property<DateTime?>("PredictedDeparture")
                        .HasColumnType("timestamptz");

                    b.Property<string>("RID")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("ScheduledArrival")
                        .HasColumnType("timestamptz");

                    b.Property<DateTime?>("ScheduledDeparture")
                        .HasColumnType("timestamptz");

                    b.Property<string>("TimetableEntryRID")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Location");

                    b.HasIndex("RID");

                    b.HasIndex("TimetableEntryRID");

                    b.ToTable("TimetableEntryLocations", (string)null);
                });

            modelBuilder.Entity("GoTravel.Darwin.Domain.Models.Database.TimetableEntryLocation", b =>
                {
                    b.HasOne("GoTravel.Darwin.Domain.Models.Database.TimetableEntry", "TimetableEntry")
                        .WithMany()
                        .HasForeignKey("RID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GoTravel.Darwin.Domain.Models.Database.TimetableEntry", null)
                        .WithMany("Locations")
                        .HasForeignKey("TimetableEntryRID");

                    b.Navigation("TimetableEntry");
                });

            modelBuilder.Entity("GoTravel.Darwin.Domain.Models.Database.TimetableEntry", b =>
                {
                    b.Navigation("Locations");
                });
#pragma warning restore 612, 618
        }
    }
}
